---
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  mvn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_PASS }}

      - name: Deploy package
        run: mvn --batch-mode -Dmaven.test.skip=true -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_PASS }} clean package deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/hetznercloud-api*.jar

  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Generate Javadocs
        run: mvn --batch-mode -Dgpg.skip=true javadoc:javadoc

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: target/site/apidocs
          branch: gh-pages