---
name: Test
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    strategy:
      matrix:
        version: [17, 21]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '${{ matrix.version }}'
          distribution: 'adopt'
          cache: maven

      - name: Download API specs from Hetzner
        run: mkdir -p build && curl -o build/hetzner.spec.json https://docs.hetzner.cloud/hetzner.spec.json && curl -o build/cloud.spec.json https://docs.hetzner.cloud/cloud.spec.json

      - name: Test
        run: mvn --batch-mode -Dgpg.skip=true test
        env:
          HCLOUD_TOKEN: ${{ secrets.HETZNER_CI_TOKEN }}
